import Head from 'next/head';
import { RECIPES_MOCK } from '../../data/recipes.data';
import { IRecipe } from '../../src/lib';

interface IRecipePageProps {
  recipe: IRecipe;
  footer: string;
}

const Recipe: React.FC<IRecipePageProps> = ({
  recipe,
  footer,
}) => {
  const { title } = recipe;

  return (
    <div>
      <Head>
        <title>Veganom - Recipe🥦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          🍲 {title}
        </h1>
      </main>
      <footer className={'footer'}>
        {footer}
      </footer>
    </div>
  )
};

export default Recipe;

export async function getServerSideProps(context: any) {
  return {
    props: {
      footer: 'xyz',
      recipe: (context.query.id) ? RECIPES_MOCK.find(a => a.id === +context.query.id) : {},
    },
  };
}
