import Head from 'next/head';

interface IRecipePageProps {
  name: string;
  footer: string;
}

const Recipe: React.FC<IRecipePageProps> = ({
  name,
  footer,
}) => {
  return (
    <div>
      <Head>
        <title>Veganom - Recipe🥦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          🍲 {name}
        </h1>
      </main>
      <footer className={'footer'}>
        {footer}
      </footer>
    </div>
  )
};

export default Recipe;

export async function getServerSideProps(context: any) {
  console.log('CONTEXT', context);
  return {
    props: {
      footer: 'xyz',
      name: 'Vegan Lasagne',
    },
  };
}
