import Head from 'next/head';
import { RecipeCard } from '../src/components';
import { FlexRowContainer } from '../src/components/common';

interface IHomePageProps {
  data: {
    footer: string;
  };
}

const Home: React.FC<IHomePageProps> = ({
  data,
}) => {
  return (
    <div>
      <Head>
        <title>Veganom 🥦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1
          style={{
            margin: '10px 20px'
          }}
        >
          Welcome to <a href="https://nextjs.org">Veganom 🥦</a>
        </h1>
        <FlexRowContainer>
          <RecipeCard />  
          <RecipeCard />
          <RecipeCard />
        </FlexRowContainer>
      </main>
      <footer
        style={{
          margin: '10px 20px',
        }}
        className={'footer'}
      >
        {data.footer}
      </footer>
    </div>
  )
};

export default Home;

export async function getStaticProps(context: any) {
  console.log('CONTEXT', context);
  return {
    props: {
      data: {
        footer: 'xyz',
      },
    },
  };
}
